/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

import DAO.ProdutoDAO;
import Model.ProdutoTableModel;
import Objetos.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class CadastroProduto extends javax.swing.JFrame {

    ProdutoTableModel pt = new ProdutoTableModel();

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        jTabelaProd.setModel(pt);
        pt.recarregaTabela();
    }

    public void limparCadastro() {
        jTDescricaoProd.setText("");
        jTValCustoProd.setText("");
        jTValVendaProd.setText("");
        jTQtdeProd.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTValCustoProd = new javax.swing.JTextField();
        jTQtdeProd = new javax.swing.JTextField();
        jTValVendaProd = new javax.swing.JTextField();
        jBCadastrarProd = new javax.swing.JButton();
        jBAlterarProd = new javax.swing.JButton();
        jBExcluirProd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTDescricaoProd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaProd = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBCadastrarProd.setText("Cadastrar");
        jBCadastrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarProdActionPerformed(evt);
            }
        });

        jBAlterarProd.setText("Alterar");
        jBAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarProdActionPerformed(evt);
            }
        });

        jBExcluirProd.setText("Excluir");
        jBExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirProdActionPerformed(evt);
            }
        });

        jButton1.setText("Gerenciar Medicamentos");

        jTextField1.setText("Pesquisa");

        jButton2.setText("Realizar Pesquisa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Descrição:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Valor de Venda:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Valor de Custo:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Produto");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Quantidade:");

        jTabelaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabelaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBCadastrarProd)
                        .addGap(29, 29, 29)
                        .addComponent(jBAlterarProd)
                        .addGap(33, 33, 33)
                        .addComponent(jBExcluirProd)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(279, 279, 279))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTValCustoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDescricaoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTValVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)
                        .addComponent(jTQtdeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1418, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTDescricaoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jTQtdeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTValCustoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTValVendaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarProd)
                    .addComponent(jBAlterarProd)
                    .addComponent(jBExcluirProd)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarProdActionPerformed
        try {
            ProdutoDAO pdao = new ProdutoDAO();
            Produto p = new Produto();

            p.setDescProd(jTDescricaoProd.getText());
            p.setQtdeProd(Integer.parseInt(jTQtdeProd.getText()));
            p.setValCusto(Double.parseDouble(jTValCustoProd.getText()));
            p.setValVenda(Double.parseDouble(jTValVendaProd.getText()));

            pdao.create(p);
            pt.recarregaTabela();
            limparCadastro();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar dados" + e);
        }


    }//GEN-LAST:event_jBCadastrarProdActionPerformed

    private void jBAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarProdActionPerformed

        try {

            if (jTabelaProd.getSelectedRow() != -1) {
                pt.setValueAt(jTDescricaoProd.getText(), jTabelaProd.getSelectedRow(), 0);
                pt.setValueAt(jTValCustoProd.getText(), jTabelaProd.getSelectedRow(), 1);
                pt.setValueAt(jTValVendaProd.getText(), jTabelaProd.getSelectedRow(), 2);
                pt.setValueAt(jTQtdeProd.getText(), jTabelaProd.getSelectedRow(), 3);

                Produto p = pt.pegaDadosLinha(jTabelaProd.getSelectedRow());
                ProdutoDAO pdao = new ProdutoDAO();

                pdao.update(p);
                pt.recarregaTabela();
                limparCadastro();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha ao atualizar dados: " + e);
        }


    }//GEN-LAST:event_jBAlterarProdActionPerformed

    private void jBExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirProdActionPerformed

        if (jTabelaProd.getSelectedRow() != -1) {
            Produto p = pt.pegaDadosLinha(jTabelaProd.getSelectedRow());
            ProdutoDAO pdao = new ProdutoDAO();

            pdao.delete(p);
            pt.recarregaTabela();
            limparCadastro();

        }


    }//GEN-LAST:event_jBExcluirProdActionPerformed

    private void jTabelaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaProdMouseClicked

        Produto p = pt.pegaDadosLinha(jTabelaProd.getSelectedRow());

        jTDescricaoProd.setText(p.getDescProd());
        jTValCustoProd.setText(String.valueOf(p.getValCusto()));
        jTValVendaProd.setText(String.valueOf(p.getValVenda()));
        jTQtdeProd.setText(String.valueOf(p.getQtdeProd()));

    }//GEN-LAST:event_jTabelaProdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterarProd;
    private javax.swing.JButton jBCadastrarProd;
    private javax.swing.JButton jBExcluirProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDescricaoProd;
    private javax.swing.JTextField jTQtdeProd;
    private javax.swing.JTextField jTValCustoProd;
    private javax.swing.JTextField jTValVendaProd;
    private javax.swing.JTable jTabelaProd;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
